### ISSUE TITLE
UTF-8 Messages ?

### ISSUE THREAD

**Issue by 316k** [Hete/kohana-mail#14]
@arteymix: Sending utf-8 messages seems to be unimplemented, or at least undocumented.

**Comment by arteymix** [comment]
You have to specifiy the appropriate content-type, the body is just bytes anyway.

``` php
Mailer::factory()
    ->content_type('text/html; charset=utf-8') // or ->headers('Content-Type', 'text/html; charset=utf-8')
    ->body(View::factory('your-unicode-view'))
    ->send($to);
```

It is document right here https://github.com/Hete/kohana-mail/blob/3.3/master/classes/Kohana/Mail/Sender.php#L110

**Comment by 316k** [comment]
Yeah... Maybe we should put that somewhere in the README.md, I wouldn't have guessed by myself I had to look in the Mail_Sender PHPDoc to find it.

**Comment by 316k** [comment]
Is it me, or wouldn't `content_type('text/html; charset=utf-8')` work with that line ? : 

``` PHP
...
    if ($this->content_type() === 'text/html')
...
```

https://github.com/Hete/kohana-mail/blob/3.3/master/classes/Kohana/Mail/Sender/PEAR.php#L49

**Comment by arteymix** [comment]
Yeah, effectively.. I will change the line for a prefix check.
