### ISSUE TITLE
Mailchimp Sender

### ISSUE THREAD

**Issue by rakucmr** [Hete/kohana-mail#9]
Can you add Mailchimp sender or other similar services?

**Comment by arteymix** [comment]
You can send mail on [Mailchimp using SMTP protocol](http://help.mandrill.com/home).

PEAR SMTP works, but it's real crap. I think I should implement something like a PHPMailer backend #10.

**Comment by arteymix** [comment]
If you want, you can use PEAR for now.

``` php
return array(
    'mailchimp' => array(
        'sender' => 'PEAR_SMTP',
        'options' => array(
            'host' => 'smtp.mandrillapp.com',
            'username' => '', // mailchimp username
            'password' => '' // mailchimp api key
        )
    )
);
```

``` php
Mailer::factory('mailchimp')
    ->subject('')
    ->body('')
    ->send('johndoe@example.com');
```

**Comment by rakucmr** [comment]
Thank you, I will use like this until you integrate PHPMailer or SWIFTmailer

**Comment by arteymix** [comment]
I will integrate it in the 3.3/develop ;)

2014-07-22 10:23 GMT-04:00 Razvan notifications@github.com:

> Thank you, I will use like this until you integrate PHPMailer or
> SWIFTmailer
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Hete/kohana-mail/issues/9#issuecomment-49745511.

## 

Guillaume Poirier-Morency guillaumepoiriermorency@gmail.com

Développeur Web chez  http://www.hete.ca

**Comment by arteymix** [comment]
PHPMailer is fully integrated!
